#pragma once

enum ID {
	CONNECTED_PING = 0x00,
	UNCONNECTED_PING = 0x01,
	UNCONNECTED_PING_OPEN_CONNECTIONS = 0x02,
	CONNECTED_PONG = 0x03,
	
	OPEN_CONNECTION_REQUEST_1 = 0x05,
	
	UNCONNECTED_PONG = 0x1c,
	
	UNKNOWN = 0xFF
};