#pragma once

enum ID {
	CONNECTED_PING = 0x00,
	UNCONNECTED_PING = 0x01,
	UNCONNECTED_PING_OPEN_CONNECTIONS = 0x02,
	CONNECTED_PONG = 0x03,
	
	OPEN_CONNECTION_REQUEST_1 = 0x05,
	OPEN_CONNECTION_REPLY_1 = 0x06,
	OPEN_CONNECTION_REQUEST_2 = 0x07,
	OPEN_CONNECTION_REPLY_2 = 0x08,
	CONNECTION_REQUEST = 0x09,
	CONNECTION_REQUEST_ACCEPTED = 0x10,
	NEW_INCOMING_CONNECTION = 0x13,
	DISCONNECT = 0x15,
	INCOMPATIBLE_PROTOCOL = 0x19,
	UNCONNECTED_PONG = 0x1c,
	
	NACK = 0xa0,
	ACK = 0xc0,
	
	GAME_PACKET = 0xfe,
	
	
	UNKNOWN = 0xFF
};